---
- hosts: localhost
  become: true
  tasks:
    - name: Creating new File
      file:
        dest: /home/devh/sample-file.txt
        state: touch

    - name: Creating new Directory
      file:
        dest: /home/devh/sample-dir
        state: directory
